on: 
  push:
    branches:
      - release

jobs:
  build:
    strategy:
      matrix:
        godot: [3.2.1]

    runs-on: ubuntu-latest
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v2.1.0

    - name: export game
      uses: firebelley/godot-export@v2.1.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{ matrix.godot }}/Godot_v${{ matrix.godot }}-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{ matrix.godot }}/Godot_v${{ matrix.godot }}-stable_export_templates.tpz
        relative_project_path: ./src/
        create_release: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Look at result
      run: |
        ls -la /home/runner/.local/share/godot/builds/
        ls -la /home/runner/.local/share/godot/builds/*
