on: 
  push:
    branches:
      - release

jobs:
  build:
    strategy:
      matrix:
        godot: [3.2.1]

    runs-on: ubuntu-latest
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v2.1.0

    - name: Mock content
      run: |
        mkdir -p /home/runner/.local/share/godot/builds/HTML5
        echo "Hello world" > /home/runner/.local/share/godot/builds/HTML5/index.html

    - name: Publish to GitHub pages
      run: ./export/export-to-gh-pages.sh /home/runner/.local/share/godot/builds/HTML5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
